### ISSUE TITLE
AI / Npc and inventory stuff

### ISSUE THREAD

**Issue by SRTCrispy** [SolidRusT/srt-nolag-platform#6]
I want to get rid of the car npc and the convoys and decreace the chance of gun drops from scientists also if theres a way to get rid of the thing where if i hover loot a ak so it goes into a box all the aks in my invintory go in the box too

**Comment by smokeweaver** [comment]
issue #1 - Convoy and TrafficDrivers
 - just remove these two mods
 
 Issue #2 gun drop from scientist is in the NPCDropGun.json file under defaults/oxide/config
 
 issue #3 - what the fuck are you talking about here. lost me
